"""
NexSandglass — 第二层：投石问路 + 解密读取
===========================================
import sandglass_vault
results = sandglass_vault.search("关键词")
latest = sandglass_vault.recent(5)
"""

import logging
import mmap
import os
import re
from datetime import datetime

from sandglass_paths import _NB

_SANDGLASS = os.path.join(_NB, "sandglass.txt")
_IDX = os.path.join(_NB, "sandglass.idx")

logger = logging.getLogger(__name__)


def set_idx_path(path: str):
    """重定向投石问路索引路径——基准测试用。"""
    global _IDX
    _IDX = path

# ── idx 内存缓存（偷师 memory-os：O(1) 查 token）──
_idx_cache: dict | None = None
_idx_mtime: float = 0


# ═══════════════════════════════════════════════
# 投石问路
# ═══════════════════════════════════════════════

def _tokenize(text: str) -> set:
    """通用分词：中文2字词+英文2+字母+英文3-4字符滑动窗口（n-gram）。
    不索引单汉字（高频噪音）。"""
    tokens = set()
    t = text.lower()
    # 英文词（2+字母）
    tokens.update(re.findall(r"[a-zA-Z0-9_]{2,}", t))
    # 英文字符滑动窗口——2到4字窗口，覆盖"sup/up/port/grou/oup"等子串
    eng = "".join(re.findall(r"[a-z0-9]", t))
    for n in (2, 3, 4):
        for i in range(len(eng) - n + 1):
            tokens.add(eng[i:i + n])
    # 中文2字词
    chars = "".join(re.findall(r"[\u4e00-\u9fff]", text))
    for i in range(len(chars) - 1):
        tokens.add(chars[i : i + 2])
    return {t for t in tokens if t}


def _query_tokens(text: str) -> set:
    """搜索分词：和_tokenize相同，但单字仅当输入只有一个中文字时才保留。"""
    tokens = _tokenize(text)
    chars = "".join(re.findall(r"[\u4e00-\u9fff]", text))
    if len(chars) != 1:
        tokens -= set(chars)  # 去单字
    return tokens


def _parse_line(line: str) -> tuple:
    """返回 (ts, sender, text) 或 (None, None, None)。
    V2.4.0: 明文存储，直接返回原文。"""
    if " | " not in line:
        return None, None, None
    parts = line.strip().split(" | ", 2)
    if len(parts) < 3:
        return None, None, None
    return parts[0], parts[1], parts[2].strip()


def _write_idx(idx):
    """Write idx dict to sandglass.idx file (atomic replace)."""
    tmp = _IDX + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("# AUTO-GENERATED BY NEXSANDGLASS — DO NOT EDIT\n")
        f.write("# token:line_number,line_number,...\n")
        f.write("# delete this file and run rebuild_index() to regenerate\n")
        f.write("\n")
        for token in sorted(idx):
            f.write(f"{token}:{','.join(map(str, sorted(set(idx[token]))))}\n")
    os.replace(tmp, _IDX)


def idx_search(query: str, limit: int = 100) -> list:
    """IDX搜索：语言感知分词→倒排→返回候选行号列表"""
    try:
        idx = _sync_index()
        if not idx:
            rebuild_index()
            idx = _sync_index()
        if not idx:
            return []
        from sandglass_think import _tokenize_for_density
        tokens = _tokenize_for_density(query)
        if not tokens:
            return []
        candidate_lines = set()
        for token in tokens:
            if token in idx:
                candidate_lines.update(idx[token])
        results = []
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            for n, line in enumerate(f, 1):
                if n in candidate_lines:
                    ts, sender, text = _parse_line(line)
                    if ts and text:
                        results.append((n, ts, text))
                        if len(results) >= limit:
                            break
        return results
    except Exception:
        return []


def rebuild_index() -> int:
    """全量重建投石问路（基于解密后文本）。原子写。返回词条数。"""
    global _idx_cache
    _idx_cache = None
    try:
        if not os.path.exists(_SANDGLASS):
            return 0
        idx = {}
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            for n, line in enumerate(f, 1):
                ts, sender, text = _parse_line(line)
                if not ts:
                    continue
                for token in _tokenize(text):
                    idx.setdefault(token, []).append(n)

        _write_idx(idx)
        return len(idx)
    except Exception:
        logger.warning("sandglass: rebuild_index() failed", exc_info=True)
        return 0


def _sync_index() -> dict:
    """增量更新索引并返回内存 dict。利用缓存避免重复读盘。"""
    global _idx_cache, _idx_mtime

    try:
        if not os.path.exists(_SANDGLASS):
            _idx_cache = {}
            return {}

        total = 0
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            total = sum(1 for _ in f)

        # 缓存命中：mtime未变 + 最大行号 ≥ 总行数
        if _idx_cache is not None:
            try:
                cur_mtime = os.path.getmtime(_SANDGLASS)
                if cur_mtime != _idx_mtime:
                    _idx_cache = None  # 文件被修改过，清缓存
                    return {}  # 返回空，让调用方重建
            except Exception:
                pass  # mtime 不可用，沿用缓存
            if _idx_cache is not None:
                cached_max = 0
                for lines in _idx_cache.values():
                    if lines:
                        cached_max = max(cached_max, max(lines))
                if cached_max >= total and total > 0:
                    return _idx_cache

        # 读 idx
        idx = {}
        idx_max = 0
        if os.path.exists(_IDX):
            with open(_IDX, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("#") or ":" not in line:
                        continue
                    t, rest = line.strip().split(":", 1)
                    nums = [int(x) for x in rest.split(",") if x]
                    idx[t] = nums
                    if nums:
                        idx_max = max(idx_max, max(nums))

        if idx_max and total > 0 and idx_max > total:
            logger.warning(f"sandglass: idx行号({idx_max})超过沙漏总行数({total})，可能是手动编辑了idx文件。自动重建中...")
            return {}  # 返回空 → 触发 mmap 降级搜索。下次 rebuild_index() 会自动重建。

        if idx_max >= total:
            _idx_cache = idx
            return idx

        # 增量：追加新行
        new_indexed = 0
        last_seen_line = idx_max
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            for n, line in enumerate(f, 1):
                if n <= idx_max:
                    continue
                ts, sender, text = _parse_line(line)
                if not ts:
                    last_seen_line = n  # 无时间戳行也推进指针，避免反复扫描
                    continue
                for token in _tokenize(text):
                    idx.setdefault(token, []).append(n)
                new_indexed += 1
                last_seen_line = n

        # 如果新行数为0且idx非空——idx已经覆盖了所有有效行，直接缓存返回
        if new_indexed == 0 and idx:
            _idx_cache = idx
            try:
                _idx_mtime = os.path.getmtime(_SANDGLASS)
            except Exception:
                pass
            return idx

        # 原子写
        _write_idx(idx)

        # LRU驱逐——超过5000词条时清缓存重建（防止无限膨胀）
        # 注意：只在确实索引了新内容时才检查LRU阈值
        # 空跑增量（尾部只有无时间戳行）不应触发驱逐
        if len(idx) > 5000 and new_indexed > 0:
            _idx_cache = {}
            return {}
        _idx_cache = idx
        try: _idx_mtime = os.path.getmtime(_SANDGLASS)
        except Exception: pass
        return idx

    except Exception:
        logger.warning("sandglass: _sync_index() failed", exc_info=True)
        return _idx_cache if _idx_cache else {}


# ═══════════════════════════════════════════════
# 搜索 + 读取
# ═══════════════════════════════════════════════

def search(query: str, limit: int = 10, month: str = "") -> list:
    """搜索沙漏。返回 [(行号, 时间, 明文), ...]。
    委托给 SearchRouter 三层架构——影子沙→投石问路→mmap。"""
    try:
        from search_router import SearchRouter, ShadowSearch, Fts5Search, IdxSearch, TfidfSearch, MmapFallback
        router = SearchRouter(
            ShadowSearch(_SANDGLASS),
            Fts5Search(),
            IdxSearch(_SANDGLASS, _IDX),
            TfidfSearch(),
            MmapFallback(_SANDGLASS)
        )
        return router.search(query, limit)
    except Exception:
        return _legacy_search(query, limit, month)


def _legacy_search(query, limit, month):
    """Fallback: mmap全量扫描 → FTS5精排。只在SearchRouter不可用时触发。"""
    try:
        mmap_results = _mmap_search(query, 500, month)
        if mmap_results:
            from sandglass_sqlite import search_in, sync_incremental
            sync_incremental()
            line_nums = [r[0] for r in mmap_results[:500]]
            ranked = search_in(line_nums, query)
            if ranked:
                return [(r[0], r[1], r[2]) for r in ranked[:limit]]
        return [(r[0], r[1], r[2]) for r in mmap_results[:limit]]
    except Exception:
        logger.warning("sandglass: search(%r) failed", query, exc_info=True)
        return []



def recent(n: int = 10) -> list:
    """最近 N 条。[(行号, 时间, 明文), ...]。V2.3.9: seek逆向流式，O(N)内存。"""
    try:
        if n <= 0 or not os.path.exists(_SANDGLASS):
            return []
        
        # 逆向读取文件尾部——只加载最后几KB，不读全文件
        chunk_size = 4096
        with open(_SANDGLASS, "rb") as f:
            f.seek(0, 2)  # 跳到文件末尾
            file_size = f.tell()
            
            lines_found = []
            buffer = b""
            pos = file_size
            
            while pos > 0 and len(lines_found) < n:
                read_size = min(chunk_size, pos)
                pos -= read_size
                f.seek(pos)
                chunk = f.read(read_size)
                buffer = chunk + buffer
                lines_found = buffer.split(b"\n")
                # 保留最后N+1行
                if len(lines_found) > n + 1:
                    lines_found = lines_found[-(n + 1):]
                # 保留第一行残片到下次循环（跨chunk长行）
                buffer = b"" if len(lines_found) == 1 and not lines_found[0] else (lines_found[0] if pos > 0 else b"")
            
            # 取最后n行非空行
            lines_found = [l for l in lines_found if l.strip()][-n:]
        
        total = count()  # 用已有count()函数，不重复数文件
        results = []
        for i, line in enumerate(lines_found):
            decoded = line.decode("utf-8", errors="ignore").strip()
            ts, sender, text = _parse_line(decoded)
            if not ts:
                continue
            ln = total - len(lines_found) + i + 1
            results.append((ln, ts, text))
        return results
    except Exception:
        logger.warning("sandglass: recent(%d) failed", n, exc_info=True)
        return []


def count() -> int:
    try:
        if not os.path.exists(_SANDGLASS):
            return 0
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            return sum(1 for _ in f)
    except Exception:
        logger.warning("sandglass: count() failed", exc_info=True)
        return 0


def _mmap_search(query: str, limit: int, month: str, stage_filter: bool = False) -> list:
    """三级降级：mmap 直接内存搜索。stage_filter=True 时只扫当前阶段+上一阶段。"""
    results = []
    try:
        # 阶段过滤——缩小扫描范围
        scan_months = [month]
        if stage_filter:
            try:
                from sandglass_think import _current_stage, stage_list
                current = _current_stage()
                scan_months = [current]
                stages = stage_list()
                if len(stages) >= 2:
                    scan_months.append(stages[-2].get("name", current))
            except: pass
        with open(_SANDGLASS, "rb") as f:
            with mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ) as mm:
                line_start = 0; line_num = 0
                while line_start < len(mm):
                    line_end = mm.find(b"\n", line_start)
                    if line_end == -1: line_end = len(mm)
                    line_num += 1
                    line = mm[line_start:line_end].decode("utf-8", errors="replace")
                    ts, sender, text = _parse_line(line)
                    if ts and query.lower() in text.lower():
                        if not scan_months or any(ts.startswith(m) for m in scan_months):
                            results.append((line_num, ts, text))
                            if limit > 0 and len(results) >= limit: break
                    line_start = line_end + 1
    except Exception:
        pass
    return results


# ═══════════════════════════════════════════════
# 时间回溯
# ═══════════════════════════════════════════════

def timeline(query: str) -> dict:
    """时间回溯——按年份分层返回关键词的演变轨迹。"""
    try:
        all_results = search(query, limit=10000)
        if not all_results:
            return {}
        # 按行号升序（时间顺序），而非 reverse search 的匹配数排序
        all_results.sort(key=lambda x: x[0])

        years = {}
        for ln, ts, text in all_results:
            year = ts[:4]
            if year not in years:
                years[year] = {"count": 0, "earliest": text, "earliest_at": ts, "latest": text, "latest_at": ts}
            years[year]["count"] += 1
            years[year]["latest"] = text
            years[year]["latest_at"] = ts

        result = {}
        for year in sorted(years):
            y = years[year]
            result[year] = {"count": y["count"], "earliest": y["earliest"], "earliest_at": y["earliest_at"],
                            "latest": y["latest"], "latest_at": y["latest_at"]}
        return result
    except Exception:
        logger.warning("sandglass: timeline(%r) failed", query, exc_info=True)
        return {}

# ═══════════════════════════════════════════════
# 沙漏导入/合并 —— V2.9.3-dev
# ═══════════════════════════════════════════════

def sandglass_import(source_path: str, source_format: str = "sandglass") -> dict:
    """导入外部对话记录到沙漏。支持格式:
    - sandglass: 同格式沙漏导出 (时间戳 | 发送者 | 文本)
    - chatgpt: ChatGPT JSON 导出
    - claude: Claude 对话 JSON 导出
    - plain: 纯文本，每行一条
    
    返回 {imported: N, skipped: N, total: N}
    """
    imported = 0
    skipped = 0
    
    try:
        if source_format == "sandglass":
            imported, skipped = _import_sandglass(source_path)
        elif source_format in ("chatgpt", "claude"):
            imported, skipped = _import_json_convo(source_path, source_format)
        elif source_format == "plain":
            imported, skipped = _import_plain(source_path)
        else:
            return {"error": f"不支持格式: {source_format}"}
        
        # 导入后重建索引
        try:
            from sandglass_sqlite import sync_incremental
            sync_incremental()
        except Exception:
            pass

        # 合并
    except Exception as e:
        logger.error(f"导入失败: {e}")
        return {"error": str(e), "imported": imported, "skipped": skipped}




def sandglass_export(output_path: str = None, limit: int = None, month: str = "") -> str:
    """导出沙漏为可迁移文件。默认导出全部。
    返回导出文件路径。
    """
    if output_path is None:
        output_path = os.path.join(_NB, "sandglass_export.txt")
    
    lines = []
    if os.path.exists(_SANDGLASS):
        with open(_SANDGLASS, "r", encoding="utf-8") as src:
            for line in src:
                if month and not line.startswith(month[:7]):
                    continue
                lines.append(line)
                if limit and len(lines) >= limit:
                    break
        
        # 取最后 limit 条（从全量读取后截断）
        if limit and len(lines) > limit:
            lines = lines[-limit:]
    
    with open(output_path, "w", encoding="utf-8") as dst:
        dst.writelines(lines)
    
    return output_path

def _import_sandglass(source_path: str) -> tuple:
    """导入同格式沙漏——按行号去重"""
    # 读已有沙漏的时间戳集合
    existing_ts = set()
    if os.path.exists(_SANDGLASS):
        with open(_SANDGLASS, "r", encoding="utf-8") as f:
            for line in f:
                if " | " in line:
                    ts = line.split(" | ")[0].strip()
                    existing_ts.add(ts)
    
    imported = 0
    skipped = 0
    with open(source_path, "r", encoding="utf-8") as src:
        for line in src:
            line = line.strip()
            if not line or not line.startswith("20"):  # 跳过非时间戳行
                continue
            if " | " not in line:
                continue
            ts = line.split(" | ")[0].strip()
            if ts in existing_ts:
                skipped += 1
                continue
            
            # 追加到沙漏
            try:
                import sandglass_log
                parts = line.split(" | ", 2)
                if len(parts) >= 3:
                    sender = parts[1].strip()
                    text = parts[2].strip()
                    sandglass_log.log_message(text, sender)
                    existing_ts.add(ts)
                    imported += 1
            except Exception:
                skipped += 1
    
    return imported, skipped


def _import_json_convo(source_path: str, fmt: str) -> tuple:
    """导入 ChatGPT/Claude JSON 导出"""
    import json
    with open(source_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    imported = 0
    skipped = 0
    
    # ChatGPT 格式: [{"mapping": {...}}, ...]
    # Claude 格式: [{"chat_messages": [...]}, ...]
    messages = []
    if fmt == "chatgpt":
        for conv in (data if isinstance(data, list) else [data]):
            mapping = conv.get("mapping", {})
            for mid, node in sorted(mapping.items(), key=lambda x: x[1].get("create_time", 0) if x[1] else 0):
                if node and node.get("message"):
                    msg = node["message"]
                    role = msg.get("author", {}).get("role", "user")
                    content = "".join(p for p in (msg.get("content", {}).get("parts", []) if isinstance(msg.get("content"), dict) else []) if isinstance(p, str))
                    if content:
                        messages.append((role, content))
    elif fmt == "claude":
        for conv in (data if isinstance(data, list) else [data]):
            for msg in conv.get("chat_messages", []):
                role = msg.get("sender", "user")
                content = msg.get("text", "")
                if content:
                    messages.append((role, content))
    
    for role, text in messages:
        try:
            import sandglass_log
            sender = "user" if role in ("user", "human") else "agent"
            sandglass_log.log_message(text, sender)
            imported += 1
        except Exception:
            skipped += 1
    
    return imported, skipped


def _import_plain(source_path: str) -> tuple:
    """导入纯文本——每行一条用户消息"""
    imported = 0
    skipped = 0
    with open(source_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                import sandglass_log
                sandglass_log.log_message(line, "user")
                imported += 1
            except Exception:
                skipped += 1
    return imported, skipped
